### ISSUE TITLE
Increasing Font size is croping menu/cheat manager gui word

### ISSUE THREAD

**Issue by ajay9634** [Lumince/Dolphin-MMJR2#5]
![Screenshot_2022-03-10-15-45-26-492_org dolphinemu mmjr](https://user-images.githubusercontent.com/78233144/157642882-ada2aa09-2830-4cbf-895f-e30fbd6ac65d.jpg)
This is small font size

![Screenshot_2022-03-10-15-44-51-820_org dolphinemu mmjr](https://user-images.githubusercontent.com/78233144/157642934-751fef68-06d9-47fc-93f5-e48e8d5c19b3.jpg)
This is large font size

**Comment by Lumince** [comment]
This is an issue with Official Dolphin. Not something I can fix
